path:
  spe_classifier_ckpt: ""
  ckpt_path: "/home/aip000/tts/models/FastSpeech2_moh_spe/output/ckpt/moh-30m-fork" # change this
  log_path: "/home/aip000/tts/models/FastSpeech2_moh_spe/output/log/moh-30m-fork" # change this
  result_path: "/home/aip000/tts/models/FastSpeech2_moh_spe/output/result/moh-30m-fork" # change this
optimizer:
  batch_size: 16
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
step:
  total_step: 100000
  log_step: 100
  synth_step: 1000
  val_step: 1000
  save_step: 50000
